sudo: required

language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "at-12"
    token: ${SONAR_TOKEN}

script:
  - ./gradlew check
  - sonar-scanner
  - ./gradlew executeBDDTests -Ptoken=$PIVOTAL_TOKEN
  - ./gradlew runTests -Ptoken=$PIVOTAL_TOKEN -Prpuuid=$RP_UUID -P rplaunch=$RP_LAUNCH -Prpproject=$RP_PROJECT
